#==================================================数据源相关=========================================================
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/m-boot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: default957

#==================================================数据源相关=========================================================

#==================================================Mybatis-Plus相关===================================================



#==================================================Mybatis-Plus相关===================================================