#==================================================数据源相关=========================================================
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/m-boot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: default957
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid配置
    druid:
      #	初始化时建立物理连接的个数
      initial-size: 5
      # 最小连接池数量
      min-idle: 5
      # 最大连接池数量
      max-active: 20


#==================================================数据源相关=========================================================

#==================================================Mybatis-Plus相关===================================================
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.mantou.boot.entity
#==================================================Mybatis-Plus相关===================================================